name: Build and test design

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: false
          fetch-depth: 1
      - name: Build SoC configuration
        run: |
          cd design
          make install install_mcw
          cp ../spi-patch.diff mgmt_core_wrapper/litex
          cd mgmt_core_wrapper/litex
          git apply spi-patch.diff
          pip install -r requirements.txt
          make mgmt_soc
          
