name: Build and test design

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: false
          fetch-depth: 1
          # apparrently we can't fetch submodules with actions/checkout, because it always tries to go recursive (and we don't want that)

      - name: Prepare the repository
        run: |
          mkdir -p $GITHUB_WORKSPACE/artifacts
          git submodule update --init
          cd $GITHUB_WORKSPACE/design
          make install install_mcw
          git apply $GITHUB_WORKSPACE/patches/Makefile.patch
          cd $GITHUB_WORKSPACE/design/mgmt_core_wrapper/litex
          git apply $GITHUB_WORKSPACE/patches/caravel.py.patch

      - name: Build SoC configuration
        run: |
          cd $GITHUB_WORKSPACE/design/mgmt_core_wrapper/litex
          pip install -r requirements.txt
          make mgmt_soc
          cp csr.json $GITHUB_WORKSPACE/artifacts

      - name: Build Renode configuration
        run: |
          python3 scripts/litex_json2renode.py --auto-align dff --auto-align sram --repl design.repl $GITHUB_WORKSPACE/artifacts/csr.json
          cat design.repl scripts/design-addend.repl > $GITHUB_WORKSPACE/artifacts/design.repl
          cp scripts/design.resc $GITHUB_WORKSPACE/artifacts

      - name: Build test
        run: |
          export TEST_NAME=aes_test
          cd $GITHUB_WORKSPACE/design
          [ -f $GITHUB_WORKSPACE/patches/design.patch ] && git apply $GITHUB_WORKSPACE/patches/design.patch
          make verify-$TEST_NAME-elf
          cp $GITHUB_WORKSPACE/design/verilog/dv/$TEST_NAME/$TEST_NAME.elf $GITHUB_WORKSPACE/artifacts/test.elf

          # - name: Build design
          #   run: |
          #     wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | apt-key add -
          #     add-apt-repository --yes https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/
          #     apt -qqy update && apt -qqy install adoptopenjdk-8-hotspot
          #     #somehow install sbt and build scala files, copy them to artifacts

      - name: Verilate design
        run: |
          sudo apt -qqy update
          sudo apt -qqy install verilator
          cd verilator
          cp $GITHUB_WORKSPACE/design/verilog/rtl/aes/generated/aes.v .
          git clone --depth=1 --branch 37446-mpw_testing https://github.com/renode/renode
          cd renode
          git submodule update --init src/Infrastructure
          cd ..
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DUSER_RENODE_DIR="`pwd`/../renode"  ..
          make libVtop
          cp libVtop.so $GITHUB_WORKSPACE/artifacts

      - name: Run test
        uses: antmicro/renode-test-action@v2.0.0
        with:
          renode-version: '1.13.1+20220918git57f09419'
          tests-to-run: 'scripts/*.robot'
          artifacts-path: $GITHUB_WORKSPACE/artifacts

      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: artifacts
