name: Build and test design

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  TEST_NAME: aes_test
  DESIGN_NAME: aes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: false
          fetch-depth: 1
          # apparrently we can't fetch submodules with actions/checkout, because it always tries to go recursive (and we don't want that)

      - name: Prepare dependencies
      - run: |
          pip install -r requirements.txt  
          sudo apt -qqy update
          sudo apt -qqy install verilator

      - name: Build
        run: ./build.sh

      - name: Run test
        uses: antmicro/renode-test-action@v3.0.0
        with:
          renode-version: '1.13.1+20220918git57f09419'
          tests-to-run: 'artifacts/*.robot'
          artifacts-path: $GITHUB_WORKSPACE/artifacts

      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: artifacts
