name: Build and test design

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'

env:
  TEST_NAME: aes_test
  DESIGN_NAME: aes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: false
          fetch-depth: 1
          # apparrently we can't fetch submodules with actions/checkout, because it always tries to go recursive (and we don't want that)
      - name: Prepare the repository
        run: |
          ./prepare.sh

      - name: Prepare dependencies
        run: |
          pip install -r "$GITHUB_WORKSPACE"/design/mgmt_core_wrapper/litex/requirements.txt
          sudo apt -qqy update
          sudo apt -qqy install verilator

      - name: Build SoC configuration
        run: |
          ./build.sh soc_configuration

      - name: Build Renode configuration
        run: |
          ./build.sh renode_configuration

      - name: Build test
        run: |
          ./build.sh test

      - name: Verilate design
        run: |
          ./build.sh verilate_design

      - name: Run test
        uses: antmicro/renode-test-action@v3.0.0
        with:
          renode-version: 'latest'
          renode-arguments: '--show-log'
          tests-to-run: 'artifacts/*.robot'
          artifacts-path: $GITHUB_WORKSPACE/artifacts

      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: artifacts
